import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import RecoilProvider  from "./components/recoil-provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "leetcode clone",
  description: "Generated by create next app",
  icons:{
    icon: "/leetcode.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  "use client";
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          {children}
          <ToastContainer/>
        </RecoilProvider>
      </body>
    </html>
  );
}
